# Question 1

In the real problems, a lot of datasets in the security are not labeled, or when it is, it is not reliable. Because of this situation, an important task of a Data Analyst is to identify features in the dataset and, using probability, try to infer labels in to the dataset

**Using the provided unlabaled dataset, create a python method that calculates how likely is that a connection from IP '14.139.187.130' and the US can make a transaction at 17-01-01 06:56:17**

First we import the dataset

In [1]:
import pandas as pd


def import_dataset(filename):
    ds = pd.read_csv(filename + '.csv',
                     parse_dates=[3], infer_datetime_format=True)
    ds['datetime'] = ds['datetime'].sort_index()
    return ds

import_dataset("access_log_format-1")

,src_ip,userid,username,datetime,method,response_code,return_obj_size,dest_address,user_agent,country
0,14.139.187.130,hahiss,hahiss@optonline.net,2017-01-01 02:16:51,GET / HTTP/1.1,200,10267,https://www.google.co.in/,Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.3...,FR
1,14.139.187.130,ahuillet,ahuillet@comcast.net,2017-01-01 02:16:55,GET /GitHub-Mark.png HTTP/1.1,200,7428,http://www.secrepo.com/,Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.3...,FR
2,14.139.187.130,gtaylor,gtaylor@gmail.com,2017-01-01 02:16:56,GET /twitter-icon.png HTTP/1.1,200,27788,http://www.secrepo.com/,Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.3...,BR
3,68.180.228.229,terjesa,terjesa@sbcglobal.net,2017-01-01 02:17:59,GET /robots.txt HTTP/1.1,200,233,-,Mozilla/5.0 (compatible; Yahoo! Slurp; http://...,FR
4,68.180.228.229,smallpaul,smallpaul@optonline.net,2017-01-01 02:17:59,GET /self.logs/access.log.2015-11-01.gz HTTP/1.1,200,6465,-,Mozilla/5.0 (compatible; Yahoo! Slurp; http://...,US
...,...,...,...,...,...,...,...,...,...,...
7224,85.159.196.242,lipeng,lipeng@att.net,2017-01-04 02:54:55,GET /honeypot/Honeypot%20-%20Howto.pdf HTTP/1.1,206,65874,http://www.secrepo.com/,Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50....,BR
7225,85.159.196.242,peterhoeg,peterhoeg@hotmail.com,2017-01-04 02:54:53,GET /honeypot/Honeypot%20-%20Howto.pdf HTTP/1.1,200,1279418,http://www.secrepo.com/,Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50....,US
7226,85.159.196.242,wikinerd,wikinerd@live.com,2017-01-04 02:54:56,GET /favicon.ico HTTP/1.1,200,267,-,Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50....,BR
7227,85.159.196.242,sblack,sblack@yahoo.ca,2017-01-04 02:54:54,GET /honeypot/Honeypot%20-%20Howto.pdf HTTP/1.1,206,65867,http://www.secrepo.com/,Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50....,MX
7228,163.172.65.131,munjal,munjal@aol.com,2017-01-04 02:59:20,GET /self.logs/error.log.2016-05-03.gz HTTP/1.1,200,782,-,Mozilla/5.0 (compatible; AhrefsBot/5.2; +http:...,MX

In [3]:
ds = import_dataset("access_log_format-1")

**Now we get the transactions that that were made at 17-01-01 06:56:17**

In [5]:
def get_rows_by_time(df, ts):
    dst = df[df['datetime'] == ts]
    return dst

get_rows_by_time(ds, '2017-01-01 06:56:17')

,src_ip,userid,username,datetime,method,response_code,return_obj_size,dest_address,user_agent,country
60,47.189.17.206,pereinar,pereinar@live.com,2017-01-01 06:56:17,GET / HTTP/1.1,200,10267,http://lnkd.in,Mozilla/5.0 (iPhone; CPU iPhone OS 10_2 like M...,FR
61,47.189.17.206,mpiotr,mpiotr@yahoo.ca,2017-01-01 06:56:17,GET /twitter-icon.png HTTP/1.1,200,27787,http://www.secrepo.com/,Mozilla/5.0 (iPhone; CPU iPhone OS 10_2 like M...,BR
62,47.189.17.206,sblack,sblack@yahoo.ca,2017-01-01 06:56:17,GET /GitHub-Mark.png HTTP/1.1,200,7428,http://www.secrepo.com/,Mozilla/5.0 (iPhone; CPU iPhone OS 10_2 like M...,MX

In [6]:
def get_rows_by_ip(df, ip):
    dst = df[df['src_ip'] == ip]
    return dst

get_rows_by_ip(ds, '14.139.187.130')

,src_ip,userid,username,datetime,method,response_code,return_obj_size,dest_address,user_agent,country
0,14.139.187.130,hahiss,hahiss@optonline.net,2017-01-01 02:16:51,GET / HTTP/1.1,200,10267,https://www.google.co.in/,Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.3...,FR
1,14.139.187.130,ahuillet,ahuillet@comcast.net,2017-01-01 02:16:55,GET /GitHub-Mark.png HTTP/1.1,200,7428,http://www.secrepo.com/,Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.3...,FR
2,14.139.187.130,gtaylor,gtaylor@gmail.com,2017-01-01 02:16:56,GET /twitter-icon.png HTTP/1.1,200,27788,http://www.secrepo.com/,Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.3...,BR

In [7]:
def get_rows_by_country(df, country):
    dst = df[df['country'] == country]
    return dst

get_rows_by_country(ds, 'US')

,src_ip,userid,username,datetime,method,response_code,return_obj_size,dest_address,user_agent,country
4,68.180.228.229,smallpaul,smallpaul@optonline.net,2017-01-01 02:17:59,GET /self.logs/access.log.2015-11-01.gz HTTP/1.1,200,6465,-,Mozilla/5.0 (compatible; Yahoo! Slurp; http://...,US
5,207.46.13.146,hahiss,hahiss@att.net,2017-01-01 03:01:47,GET /self.logs/ HTTP/1.1,200,14674,-,Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Ma...,US
6,68.180.228.229,noahb,noahb@hotmail.com,2017-01-01 03:07:34,GET /maccdc2012/signatures.log.gz HTTP/1.1,200,549,-,Mozilla/5.0 (compatible; Yahoo! Slurp; http://...,US
7,123.125.67.226,ijackson,ijackson@yahoo.ca,2017-01-01 04:01:29,GET /robots.txt HTTP/1.1,200,297,-,Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebK...,US
14,195.154.191.64,blixem,blixem@att.net,2017-01-01 04:08:07,GET /udd.php HTTP/1.0,404,295,-,Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.3...,US
...,...,...,...,...,...,...,...,...,...,...
7209,54.234.104.161,jemarch,jemarch@aol.com,2017-01-04 02:52:03,GET /index.php?format=feed&type=rss HTTP/1.1,301,542,-,Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKi...,US
7213,54.234.104.161,shawnce,shawnce@verizon.net,2017-01-04 02:52:03,GET /rss.xml HTTP/1.1,301,494,-,Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKi...,US
7218,54.234.104.161,smallpaul,smallpaul@optonline.net,2017-01-04 02:52:03,GET /data/atom HTTP/1.1,404,340,-,Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKi...,US
7220,54.234.104.161,ijackson,ijackson@yahoo.ca,2017-01-04 02:52:03,GET /index.php/feed/ HTTP/1.1,404,340,-,Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKi...,US
7225,85.159.196.242,peterhoeg,peterhoeg@hotmail.com,2017-01-04 02:54:53,GET /honeypot/Honeypot%20-%20Howto.pdf HTTP/1.1,200,1279418,http://www.secrepo.com/,Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50....,US

In the data above we can see that at the datetime 2017-01-01 06:56:17 there is no value for neither US or ip: 14.139.187.130, so we can be almost sure that the intersection is 0 and therefore the probability is 0, now we prove it.

**We add boolean columns with the data to show if the entry has the data we want**

In [8]:
import numpy as np

def prepare_pivot_table(ds):
    ds['From_US'] = np.where(ds['country'] == "US", 1, 0)
    ds['From_IP'] = np.where(ds['src_ip'] == "14.139.187.130", 1, 0)
    ds['Correct_datetime'] = np.where(ds['datetime'] == "2017-01-01 06:56:17", 1, 0)
    ds['count'] = 1
    
    df = ds[['From_IP', 'From_US', 'Correct_datetime', 'count']]

    return df

df = prepare_pivot_table(ds)
df.head()

   From_IP  From_US  Correct_datetime  count
0        1        0                 0      1
1        1        0                 0      1
2        1        0                 0      1
3        0        0                 0      1
4        0        1                 0      1

In [11]:
pd.pivot_table(
    df,
    values = 'count',
    index = ['From_IP'],
    columns = ['From_US', 'Correct_datetime'],
    aggfunc = np.size,
    fill_value = 0
)

From_US              0        1
Correct_datetime     0  1     0
From_IP
0                 5417  3  1806
1                    3  0     0

Proving that there is no case in which the IP 14.139.187.130 and the US happen at the same time and neither of those values appear during the datetime 2017-01-01 06:56:17 we can now that the value of the intersection (US âˆ© 14.139.187.130 âˆ© 2017-01-01 06:56:17) is zero we then we know that: 

**0/P(2017-01-01 06:56:17)is zero**